/*
MISSION CONTROL

Documentation for Mission Control API

API version: V2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetServiceResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetServiceResponse{}

// GetServiceResponse struct for GetServiceResponse
type GetServiceResponse struct {
	Data *GetService `json:"data,omitempty"`
	Meta map[string]map[string]interface{} `json:"meta,omitempty"`
}

// NewGetServiceResponse instantiates a new GetServiceResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetServiceResponse() *GetServiceResponse {
	this := GetServiceResponse{}
	return &this
}

// NewGetServiceResponseWithDefaults instantiates a new GetServiceResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetServiceResponseWithDefaults() *GetServiceResponse {
	this := GetServiceResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetServiceResponse) GetData() GetService {
	if o == nil || IsNil(o.Data) {
		var ret GetService
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetServiceResponse) GetDataOk() (*GetService, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetServiceResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given GetService and assigns it to the Data field.
func (o *GetServiceResponse) SetData(v GetService) {
	o.Data = &v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *GetServiceResponse) GetMeta() map[string]map[string]interface{} {
	if o == nil || IsNil(o.Meta) {
		var ret map[string]map[string]interface{}
		return ret
	}
	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetServiceResponse) GetMetaOk() (map[string]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Meta) {
		return map[string]map[string]interface{}{}, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *GetServiceResponse) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given map[string]map[string]interface{} and assigns it to the Meta field.
func (o *GetServiceResponse) SetMeta(v map[string]map[string]interface{}) {
	o.Meta = v
}

func (o GetServiceResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetServiceResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	return toSerialize, nil
}

type NullableGetServiceResponse struct {
	value *GetServiceResponse
	isSet bool
}

func (v NullableGetServiceResponse) Get() *GetServiceResponse {
	return v.value
}

func (v *NullableGetServiceResponse) Set(val *GetServiceResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetServiceResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetServiceResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetServiceResponse(val *GetServiceResponse) *NullableGetServiceResponse {
	return &NullableGetServiceResponse{value: val, isSet: true}
}

func (v NullableGetServiceResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetServiceResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


