/*
MISSION CONTROL

Documentation for Mission Control API

API version: V2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ProvisionedEndpointSpoolUsageAlertThresholds type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProvisionedEndpointSpoolUsageAlertThresholds{}

// ProvisionedEndpointSpoolUsageAlertThresholds The clear ('clearPercent') and raise ('setPercent') threshold values that determine when to generate events for the percentage amount of the message spool used by all endpoints provisioned by clients for the given client profile.
type ProvisionedEndpointSpoolUsageAlertThresholds struct {
	// The clear threshold value for the message spool usage (as a percentage).
	SetPercent *int32 `json:"setPercent,omitempty"`
	// The raise threshold value for the message spool usage (as a percentage).
	ClearPercent *int32 `json:"clearPercent,omitempty"`
}

// NewProvisionedEndpointSpoolUsageAlertThresholds instantiates a new ProvisionedEndpointSpoolUsageAlertThresholds object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProvisionedEndpointSpoolUsageAlertThresholds() *ProvisionedEndpointSpoolUsageAlertThresholds {
	this := ProvisionedEndpointSpoolUsageAlertThresholds{}
	return &this
}

// NewProvisionedEndpointSpoolUsageAlertThresholdsWithDefaults instantiates a new ProvisionedEndpointSpoolUsageAlertThresholds object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProvisionedEndpointSpoolUsageAlertThresholdsWithDefaults() *ProvisionedEndpointSpoolUsageAlertThresholds {
	this := ProvisionedEndpointSpoolUsageAlertThresholds{}
	return &this
}

// GetSetPercent returns the SetPercent field value if set, zero value otherwise.
func (o *ProvisionedEndpointSpoolUsageAlertThresholds) GetSetPercent() int32 {
	if o == nil || IsNil(o.SetPercent) {
		var ret int32
		return ret
	}
	return *o.SetPercent
}

// GetSetPercentOk returns a tuple with the SetPercent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvisionedEndpointSpoolUsageAlertThresholds) GetSetPercentOk() (*int32, bool) {
	if o == nil || IsNil(o.SetPercent) {
		return nil, false
	}
	return o.SetPercent, true
}

// HasSetPercent returns a boolean if a field has been set.
func (o *ProvisionedEndpointSpoolUsageAlertThresholds) HasSetPercent() bool {
	if o != nil && !IsNil(o.SetPercent) {
		return true
	}

	return false
}

// SetSetPercent gets a reference to the given int32 and assigns it to the SetPercent field.
func (o *ProvisionedEndpointSpoolUsageAlertThresholds) SetSetPercent(v int32) {
	o.SetPercent = &v
}

// GetClearPercent returns the ClearPercent field value if set, zero value otherwise.
func (o *ProvisionedEndpointSpoolUsageAlertThresholds) GetClearPercent() int32 {
	if o == nil || IsNil(o.ClearPercent) {
		var ret int32
		return ret
	}
	return *o.ClearPercent
}

// GetClearPercentOk returns a tuple with the ClearPercent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvisionedEndpointSpoolUsageAlertThresholds) GetClearPercentOk() (*int32, bool) {
	if o == nil || IsNil(o.ClearPercent) {
		return nil, false
	}
	return o.ClearPercent, true
}

// HasClearPercent returns a boolean if a field has been set.
func (o *ProvisionedEndpointSpoolUsageAlertThresholds) HasClearPercent() bool {
	if o != nil && !IsNil(o.ClearPercent) {
		return true
	}

	return false
}

// SetClearPercent gets a reference to the given int32 and assigns it to the ClearPercent field.
func (o *ProvisionedEndpointSpoolUsageAlertThresholds) SetClearPercent(v int32) {
	o.ClearPercent = &v
}

func (o ProvisionedEndpointSpoolUsageAlertThresholds) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProvisionedEndpointSpoolUsageAlertThresholds) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SetPercent) {
		toSerialize["setPercent"] = o.SetPercent
	}
	if !IsNil(o.ClearPercent) {
		toSerialize["clearPercent"] = o.ClearPercent
	}
	return toSerialize, nil
}

type NullableProvisionedEndpointSpoolUsageAlertThresholds struct {
	value *ProvisionedEndpointSpoolUsageAlertThresholds
	isSet bool
}

func (v NullableProvisionedEndpointSpoolUsageAlertThresholds) Get() *ProvisionedEndpointSpoolUsageAlertThresholds {
	return v.value
}

func (v *NullableProvisionedEndpointSpoolUsageAlertThresholds) Set(val *ProvisionedEndpointSpoolUsageAlertThresholds) {
	v.value = val
	v.isSet = true
}

func (v NullableProvisionedEndpointSpoolUsageAlertThresholds) IsSet() bool {
	return v.isSet
}

func (v *NullableProvisionedEndpointSpoolUsageAlertThresholds) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProvisionedEndpointSpoolUsageAlertThresholds(val *ProvisionedEndpointSpoolUsageAlertThresholds) *NullableProvisionedEndpointSpoolUsageAlertThresholds {
	return &NullableProvisionedEndpointSpoolUsageAlertThresholds{value: val, isSet: true}
}

func (v NullableProvisionedEndpointSpoolUsageAlertThresholds) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProvisionedEndpointSpoolUsageAlertThresholds) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


