/*
MISSION CONTROL

Documentation for Mission Control API

API version: V2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ClientProfileResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClientProfileResponse{}

// ClientProfileResponse struct for ClientProfileResponse
type ClientProfileResponse struct {
	Data *ClientProfile `json:"data,omitempty"`
	Meta map[string]map[string]interface{} `json:"meta,omitempty"`
}

// NewClientProfileResponse instantiates a new ClientProfileResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClientProfileResponse() *ClientProfileResponse {
	this := ClientProfileResponse{}
	return &this
}

// NewClientProfileResponseWithDefaults instantiates a new ClientProfileResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClientProfileResponseWithDefaults() *ClientProfileResponse {
	this := ClientProfileResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ClientProfileResponse) GetData() ClientProfile {
	if o == nil || IsNil(o.Data) {
		var ret ClientProfile
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientProfileResponse) GetDataOk() (*ClientProfile, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ClientProfileResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given ClientProfile and assigns it to the Data field.
func (o *ClientProfileResponse) SetData(v ClientProfile) {
	o.Data = &v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *ClientProfileResponse) GetMeta() map[string]map[string]interface{} {
	if o == nil || IsNil(o.Meta) {
		var ret map[string]map[string]interface{}
		return ret
	}
	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientProfileResponse) GetMetaOk() (map[string]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Meta) {
		return map[string]map[string]interface{}{}, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *ClientProfileResponse) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given map[string]map[string]interface{} and assigns it to the Meta field.
func (o *ClientProfileResponse) SetMeta(v map[string]map[string]interface{}) {
	o.Meta = v
}

func (o ClientProfileResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClientProfileResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	return toSerialize, nil
}

type NullableClientProfileResponse struct {
	value *ClientProfileResponse
	isSet bool
}

func (v NullableClientProfileResponse) Get() *ClientProfileResponse {
	return v.value
}

func (v *NullableClientProfileResponse) Set(val *ClientProfileResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableClientProfileResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableClientProfileResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClientProfileResponse(val *ClientProfileResponse) *NullableClientProfileResponse {
	return &NullableClientProfileResponse{value: val, isSet: true}
}

func (v NullableClientProfileResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClientProfileResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


