/*
MISSION CONTROL

Documentation for Mission Control API

API version: V2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetAllServicesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAllServicesResponse{}

// GetAllServicesResponse struct for GetAllServicesResponse
type GetAllServicesResponse struct {
	Data []GetServices `json:"data,omitempty"`
	Meta map[string]map[string]interface{} `json:"meta,omitempty"`
}

// NewGetAllServicesResponse instantiates a new GetAllServicesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAllServicesResponse() *GetAllServicesResponse {
	this := GetAllServicesResponse{}
	return &this
}

// NewGetAllServicesResponseWithDefaults instantiates a new GetAllServicesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAllServicesResponseWithDefaults() *GetAllServicesResponse {
	this := GetAllServicesResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetAllServicesResponse) GetData() []GetServices {
	if o == nil || IsNil(o.Data) {
		var ret []GetServices
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAllServicesResponse) GetDataOk() ([]GetServices, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetAllServicesResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []GetServices and assigns it to the Data field.
func (o *GetAllServicesResponse) SetData(v []GetServices) {
	o.Data = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *GetAllServicesResponse) GetMeta() map[string]map[string]interface{} {
	if o == nil || IsNil(o.Meta) {
		var ret map[string]map[string]interface{}
		return ret
	}
	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAllServicesResponse) GetMetaOk() (map[string]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Meta) {
		return map[string]map[string]interface{}{}, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *GetAllServicesResponse) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given map[string]map[string]interface{} and assigns it to the Meta field.
func (o *GetAllServicesResponse) SetMeta(v map[string]map[string]interface{}) {
	o.Meta = v
}

func (o GetAllServicesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAllServicesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	return toSerialize, nil
}

type NullableGetAllServicesResponse struct {
	value *GetAllServicesResponse
	isSet bool
}

func (v NullableGetAllServicesResponse) Get() *GetAllServicesResponse {
	return v.value
}

func (v *NullableGetAllServicesResponse) Set(val *GetAllServicesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAllServicesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAllServicesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAllServicesResponse(val *GetAllServicesResponse) *NullableGetAllServicesResponse {
	return &NullableGetAllServicesResponse{value: val, isSet: true}
}

func (v NullableGetAllServicesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAllServicesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


