/*
MISSION CONTROL

Documentation for Mission Control API

API version: V2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ServiceClassResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceClassResponse{}

// ServiceClassResponse struct for ServiceClassResponse
type ServiceClassResponse struct {
	Data *ServiceClass `json:"data,omitempty"`
	Meta map[string]map[string]interface{} `json:"meta,omitempty"`
}

// NewServiceClassResponse instantiates a new ServiceClassResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceClassResponse() *ServiceClassResponse {
	this := ServiceClassResponse{}
	return &this
}

// NewServiceClassResponseWithDefaults instantiates a new ServiceClassResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceClassResponseWithDefaults() *ServiceClassResponse {
	this := ServiceClassResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ServiceClassResponse) GetData() ServiceClass {
	if o == nil || IsNil(o.Data) {
		var ret ServiceClass
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceClassResponse) GetDataOk() (*ServiceClass, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ServiceClassResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given ServiceClass and assigns it to the Data field.
func (o *ServiceClassResponse) SetData(v ServiceClass) {
	o.Data = &v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *ServiceClassResponse) GetMeta() map[string]map[string]interface{} {
	if o == nil || IsNil(o.Meta) {
		var ret map[string]map[string]interface{}
		return ret
	}
	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceClassResponse) GetMetaOk() (map[string]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Meta) {
		return map[string]map[string]interface{}{}, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *ServiceClassResponse) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given map[string]map[string]interface{} and assigns it to the Meta field.
func (o *ServiceClassResponse) SetMeta(v map[string]map[string]interface{}) {
	o.Meta = v
}

func (o ServiceClassResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceClassResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	return toSerialize, nil
}

type NullableServiceClassResponse struct {
	value *ServiceClassResponse
	isSet bool
}

func (v NullableServiceClassResponse) Get() *ServiceClassResponse {
	return v.value
}

func (v *NullableServiceClassResponse) Set(val *ServiceClassResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceClassResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceClassResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceClassResponse(val *ServiceClassResponse) *NullableServiceClassResponse {
	return &NullableServiceClassResponse{value: val, isSet: true}
}

func (v NullableServiceClassResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceClassResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


