/*
MISSION CONTROL

Documentation for Mission Control API

API version: V2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CertificateAuthority type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CertificateAuthority{}

// CertificateAuthority The certificate authority.
type CertificateAuthority struct {
	// Name
	Name *string `json:"name,omitempty"`
}

// NewCertificateAuthority instantiates a new CertificateAuthority object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCertificateAuthority() *CertificateAuthority {
	this := CertificateAuthority{}
	return &this
}

// NewCertificateAuthorityWithDefaults instantiates a new CertificateAuthority object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCertificateAuthorityWithDefaults() *CertificateAuthority {
	this := CertificateAuthority{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CertificateAuthority) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CertificateAuthority) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CertificateAuthority) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CertificateAuthority) SetName(v string) {
	o.Name = &v
}

func (o CertificateAuthority) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CertificateAuthority) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableCertificateAuthority struct {
	value *CertificateAuthority
	isSet bool
}

func (v NullableCertificateAuthority) Get() *CertificateAuthority {
	return v.value
}

func (v *NullableCertificateAuthority) Set(val *CertificateAuthority) {
	v.value = val
	v.isSet = true
}

func (v NullableCertificateAuthority) IsSet() bool {
	return v.isSet
}

func (v *NullableCertificateAuthority) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCertificateAuthority(val *CertificateAuthority) *NullableCertificateAuthority {
	return &NullableCertificateAuthority{value: val, isSet: true}
}

func (v NullableCertificateAuthority) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCertificateAuthority) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


