/*
MISSION CONTROL

Documentation for Mission Control API

API version: V2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the LdapProfile type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LdapProfile{}

// LdapProfile The LDAP profiles configured for the event broker service.
type LdapProfile struct {
	// The name of the LDAP profile.
	Name *string `json:"name,omitempty"`
}

// NewLdapProfile instantiates a new LdapProfile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLdapProfile() *LdapProfile {
	this := LdapProfile{}
	return &this
}

// NewLdapProfileWithDefaults instantiates a new LdapProfile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLdapProfileWithDefaults() *LdapProfile {
	this := LdapProfile{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *LdapProfile) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LdapProfile) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *LdapProfile) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *LdapProfile) SetName(v string) {
	o.Name = &v
}

func (o LdapProfile) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LdapProfile) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableLdapProfile struct {
	value *LdapProfile
	isSet bool
}

func (v NullableLdapProfile) Get() *LdapProfile {
	return v.value
}

func (v *NullableLdapProfile) Set(val *LdapProfile) {
	v.value = val
	v.isSet = true
}

func (v NullableLdapProfile) IsSet() bool {
	return v.isSet
}

func (v *NullableLdapProfile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLdapProfile(val *LdapProfile) *NullableLdapProfile {
	return &NullableLdapProfile{value: val, isSet: true}
}

func (v NullableLdapProfile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLdapProfile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


