/*
MISSION CONTROL

Documentation for Mission Control API

API version: V2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the LoginCredential type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LoginCredential{}

// LoginCredential The login credentials for the event broker service.
type LoginCredential struct {
	// The username to log into the event broker service.
	Username *string `json:"username,omitempty"`
	// The password to log into the event broker service.
	Password *string `json:"password,omitempty"`
}

// NewLoginCredential instantiates a new LoginCredential object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLoginCredential() *LoginCredential {
	this := LoginCredential{}
	return &this
}

// NewLoginCredentialWithDefaults instantiates a new LoginCredential object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLoginCredentialWithDefaults() *LoginCredential {
	this := LoginCredential{}
	return &this
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *LoginCredential) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoginCredential) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *LoginCredential) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *LoginCredential) SetUsername(v string) {
	o.Username = &v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *LoginCredential) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoginCredential) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *LoginCredential) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *LoginCredential) SetPassword(v string) {
	o.Password = &v
}

func (o LoginCredential) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LoginCredential) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	return toSerialize, nil
}

type NullableLoginCredential struct {
	value *LoginCredential
	isSet bool
}

func (v NullableLoginCredential) Get() *LoginCredential {
	return v.value
}

func (v *NullableLoginCredential) Set(val *LoginCredential) {
	v.value = val
	v.isSet = true
}

func (v NullableLoginCredential) IsSet() bool {
	return v.isSet
}

func (v *NullableLoginCredential) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoginCredential(val *LoginCredential) *NullableLoginCredential {
	return &NullableLoginCredential{value: val, isSet: true}
}

func (v NullableLoginCredential) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoginCredential) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


