/*
MISSION CONTROL

Documentation for Mission Control API

API version: V2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the SpoolScaleUpCapabilityInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SpoolScaleUpCapabilityInfo{}

// SpoolScaleUpCapabilityInfo struct for SpoolScaleUpCapabilityInfo
type SpoolScaleUpCapabilityInfo struct {
	// The current state of  the Scalable Message Spool Size feature. The values can be 'INPROGRESS', 'SUPPORTED', 'NOT SUPPORTED', or 'UNKNOWN'.
	SpoolScaleUpCapabilityState *string `json:"spoolScaleUpCapabilityState,omitempty"`
	// The time of the last test was performed, in ISO 8601 date/time format.
	SpoolScaleUpTestTimestamp *time.Time `json:"spoolScaleUpTestTimestamp,omitempty"`
	// Message resulting from a self-test of support for the Scalable Message Spool Size feature.
	SpoolScaleUpTestMessage *string `json:"spoolScaleUpTestMessage,omitempty"`
}

// NewSpoolScaleUpCapabilityInfo instantiates a new SpoolScaleUpCapabilityInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSpoolScaleUpCapabilityInfo() *SpoolScaleUpCapabilityInfo {
	this := SpoolScaleUpCapabilityInfo{}
	return &this
}

// NewSpoolScaleUpCapabilityInfoWithDefaults instantiates a new SpoolScaleUpCapabilityInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSpoolScaleUpCapabilityInfoWithDefaults() *SpoolScaleUpCapabilityInfo {
	this := SpoolScaleUpCapabilityInfo{}
	return &this
}

// GetSpoolScaleUpCapabilityState returns the SpoolScaleUpCapabilityState field value if set, zero value otherwise.
func (o *SpoolScaleUpCapabilityInfo) GetSpoolScaleUpCapabilityState() string {
	if o == nil || IsNil(o.SpoolScaleUpCapabilityState) {
		var ret string
		return ret
	}
	return *o.SpoolScaleUpCapabilityState
}

// GetSpoolScaleUpCapabilityStateOk returns a tuple with the SpoolScaleUpCapabilityState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpoolScaleUpCapabilityInfo) GetSpoolScaleUpCapabilityStateOk() (*string, bool) {
	if o == nil || IsNil(o.SpoolScaleUpCapabilityState) {
		return nil, false
	}
	return o.SpoolScaleUpCapabilityState, true
}

// HasSpoolScaleUpCapabilityState returns a boolean if a field has been set.
func (o *SpoolScaleUpCapabilityInfo) HasSpoolScaleUpCapabilityState() bool {
	if o != nil && !IsNil(o.SpoolScaleUpCapabilityState) {
		return true
	}

	return false
}

// SetSpoolScaleUpCapabilityState gets a reference to the given string and assigns it to the SpoolScaleUpCapabilityState field.
func (o *SpoolScaleUpCapabilityInfo) SetSpoolScaleUpCapabilityState(v string) {
	o.SpoolScaleUpCapabilityState = &v
}

// GetSpoolScaleUpTestTimestamp returns the SpoolScaleUpTestTimestamp field value if set, zero value otherwise.
func (o *SpoolScaleUpCapabilityInfo) GetSpoolScaleUpTestTimestamp() time.Time {
	if o == nil || IsNil(o.SpoolScaleUpTestTimestamp) {
		var ret time.Time
		return ret
	}
	return *o.SpoolScaleUpTestTimestamp
}

// GetSpoolScaleUpTestTimestampOk returns a tuple with the SpoolScaleUpTestTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpoolScaleUpCapabilityInfo) GetSpoolScaleUpTestTimestampOk() (*time.Time, bool) {
	if o == nil || IsNil(o.SpoolScaleUpTestTimestamp) {
		return nil, false
	}
	return o.SpoolScaleUpTestTimestamp, true
}

// HasSpoolScaleUpTestTimestamp returns a boolean if a field has been set.
func (o *SpoolScaleUpCapabilityInfo) HasSpoolScaleUpTestTimestamp() bool {
	if o != nil && !IsNil(o.SpoolScaleUpTestTimestamp) {
		return true
	}

	return false
}

// SetSpoolScaleUpTestTimestamp gets a reference to the given time.Time and assigns it to the SpoolScaleUpTestTimestamp field.
func (o *SpoolScaleUpCapabilityInfo) SetSpoolScaleUpTestTimestamp(v time.Time) {
	o.SpoolScaleUpTestTimestamp = &v
}

// GetSpoolScaleUpTestMessage returns the SpoolScaleUpTestMessage field value if set, zero value otherwise.
func (o *SpoolScaleUpCapabilityInfo) GetSpoolScaleUpTestMessage() string {
	if o == nil || IsNil(o.SpoolScaleUpTestMessage) {
		var ret string
		return ret
	}
	return *o.SpoolScaleUpTestMessage
}

// GetSpoolScaleUpTestMessageOk returns a tuple with the SpoolScaleUpTestMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SpoolScaleUpCapabilityInfo) GetSpoolScaleUpTestMessageOk() (*string, bool) {
	if o == nil || IsNil(o.SpoolScaleUpTestMessage) {
		return nil, false
	}
	return o.SpoolScaleUpTestMessage, true
}

// HasSpoolScaleUpTestMessage returns a boolean if a field has been set.
func (o *SpoolScaleUpCapabilityInfo) HasSpoolScaleUpTestMessage() bool {
	if o != nil && !IsNil(o.SpoolScaleUpTestMessage) {
		return true
	}

	return false
}

// SetSpoolScaleUpTestMessage gets a reference to the given string and assigns it to the SpoolScaleUpTestMessage field.
func (o *SpoolScaleUpCapabilityInfo) SetSpoolScaleUpTestMessage(v string) {
	o.SpoolScaleUpTestMessage = &v
}

func (o SpoolScaleUpCapabilityInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SpoolScaleUpCapabilityInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SpoolScaleUpCapabilityState) {
		toSerialize["spoolScaleUpCapabilityState"] = o.SpoolScaleUpCapabilityState
	}
	if !IsNil(o.SpoolScaleUpTestTimestamp) {
		toSerialize["spoolScaleUpTestTimestamp"] = o.SpoolScaleUpTestTimestamp
	}
	if !IsNil(o.SpoolScaleUpTestMessage) {
		toSerialize["spoolScaleUpTestMessage"] = o.SpoolScaleUpTestMessage
	}
	return toSerialize, nil
}

type NullableSpoolScaleUpCapabilityInfo struct {
	value *SpoolScaleUpCapabilityInfo
	isSet bool
}

func (v NullableSpoolScaleUpCapabilityInfo) Get() *SpoolScaleUpCapabilityInfo {
	return v.value
}

func (v *NullableSpoolScaleUpCapabilityInfo) Set(val *SpoolScaleUpCapabilityInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableSpoolScaleUpCapabilityInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableSpoolScaleUpCapabilityInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSpoolScaleUpCapabilityInfo(val *SpoolScaleUpCapabilityInfo) *NullableSpoolScaleUpCapabilityInfo {
	return &NullableSpoolScaleUpCapabilityInfo{value: val, isSet: true}
}

func (v NullableSpoolScaleUpCapabilityInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSpoolScaleUpCapabilityInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


